<?php
    $nombreUsuario = $_POST['nombreUsuario'];
    $nombreCompleto = $_POST['nombreCompleto'];
    $contrasena = $_POST['contrasena'];
    $confirmarContrasena = $_POST['confirmarContrasena'];
    $correoElectronico = $_POST['correoElectronico'];
    $sexo = $_POST['sexo'];
    $hobbies = $_POST['hobbies'];
    $estadoCivil = $_POST['estadoCivil'];
    $calle = $_POST['calle'];
    $numeroInterior = $_POST['numeroInterior'];
    $colonia = $_POST['colonia'];
    $estado = $_POST['estado'];
    $pais = $_POST['pais'];
    $cp = $_POST['cp'];


echo "<table border='1'>";
echo "<tr>";
echo "<th>Nombre de usuario</th>";
echo "<td>$nombreUsuario</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Nombre completo</th>";
echo "<td>$nombreCompleto</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Contraseña</th>";
echo "<td>$contrasena</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Correo electrónico</th>";
echo "<td>$correoElectronico</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Sexo</th>";
echo "<td>$sexo</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Hobbies</th>";
echo "<td>$hobbies</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Estado civil</th>";
echo "<td>$estadoCivil</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Calle</th>";
echo "<td>$calle</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Número interior</th>";
echo "<td>$numeroInterior</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Colonia</th>";
echo "<td>$colonia</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Estado</th>";
echo "<td>$estado</td>";
echo "</tr>";
echo "<tr>";
echo "<th>País</th>";
echo "<td>$pais</td>";
echo "</tr>";
echo "<tr>";
echo "<th>Código postal</th>";
echo "<td>$cp</td>";
echo "</tr>";
echo "</table>";
?>